<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>StripeHarness</AssemblyName>
    <RootNamespace>StripeHarness</RootNamespace>
    <LangVersion>9.0</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\out\harness\</OutputPath>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <NoWarn>CS0618;CS0168;CS0219</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RhinoCommon" Version="8.30.26103.11001" />
    <PackageReference Include="System.Collections.Immutable" Version="7.0.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\src\StripePattern.cs" />
    <Compile Include="..\src\Engraver.cs" />
  </ItemGroup>

</Project>
