'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { pathToFileURL } = require('url');
const { chromium } = require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT = __dirname;
const checks = [];
const check = (name, ok, detail = '') => { checks.push({ name, ok: !!ok, detail }); console.log((ok ? 'PASS ' : 'FAIL ') + name + (detail ? ' | ' + detail : '')); };
const hash = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase();
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--disable-background-networking', '--no-first-run'] });
  const context = await browser.newContext({ viewport: { width: 1280, height: 960 }, deviceScaleFactor: 1, offline: true });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(pathToFileURL(path.join(ROOT, 'index.html')).href);
  await page.waitForFunction(() => window.preview && window.preview.ready, { timeout: 30000 });
  await page.waitForTimeout(350);
  check('five plugin rows', await page.locator('.plugin-row').count() === 5);
  check('no horizontal overflow at 1280px', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(ROOT, '01-launcher-light.png') });
  await page.locator('[data-theme="dark"]').click();
  await page.waitForTimeout(200);
  check('dark theme applied', await page.locator('body').evaluate(e => e.classList.contains('dark')));
  await page.screenshot({ path: path.join(ROOT, '02-launcher-dark.png') });
  await page.locator('[data-theme="light"]').click();
  await page.locator('#pluginSearch').fill('泰森');
  check('search exact match', await page.locator('.plugin-row:visible').count() === 1);
  await page.locator('#pluginSearch').fill('not-a-plugin');
  check('search empty state', await page.locator('#emptySearch').isVisible());
  await page.locator('#pluginSearch').fill('');
  const kinds = ['stripe', 'halftone', 'voronoi', 'radialdots', 'vape'];
  for (let i = 0; i < kinds.length; i++) {
    const kind = kinds[i];
    await page.evaluate(k => window.preview.openPanel(k), kind);
    await page.waitForTimeout(350);
    const picked = await page.locator('#panelBody .pick-button').count();
    const expectedPicks = await page.evaluate(k => window.PanelData[k].picks.length, kind);
    check(kind + ' correct selection buttons', picked === expectedPicks, String(picked));
    check(kind + ' panel visible', await page.locator('#panelOverlay').isVisible());
    check(kind + ' parameter defaults present', await page.locator('#panelBody input[type="number"]').count() > 0);
    check(kind + ' illustrative SVG present', await page.locator('#viewportArt svg').count() > 0);
    if (picked) {
      check(kind + ' generation disabled before selection', await page.locator('#generateButton').isDisabled());
      await page.locator('#panelBody .pick-button').first().click();
      check(kind + ' red to green selection', await page.locator('#panelBody .pick-button').first().evaluate(e => e.classList.contains('picked')));
    }
    const pair = page.locator('#panelBody input[type="number"]').first();
    const original = await pair.inputValue();
    const max = Number(await pair.getAttribute('max'));
    const testValue = Math.min(max, Number(original) + 0.5);
    await pair.fill(String(testValue));
    await pair.dispatchEvent('input');
    await pair.dispatchEvent('change');
    const rangeValue = Number(await page.locator('#panelBody input[type="range"]').first().inputValue());
    const sliderMax = Number(await page.locator('#panelBody input[type="range"]').first().getAttribute('max'));
    check(kind + ' numeric/slider sync', Math.abs(rangeValue - Math.min(testValue, sliderMax)) < 0.001, String(rangeValue));
    await pair.fill(original); await pair.dispatchEvent('input'); await pair.dispatchEvent('change');
    await page.locator('#panelBody').evaluate(e => e.scrollTop = 0);
    await page.screenshot({ path: path.join(ROOT, String(i + 3).padStart(2, '0') + '-panel-' + kind + '.png') });
    await page.locator('#panelBody').evaluate(e => e.scrollTop = e.scrollHeight);
    await page.screenshot({ path: path.join(ROOT, 'detail-' + kind + '.png') });
    await page.keyboard.press('Escape');
    await page.waitForTimeout(220);
    check(kind + ' closes without invisible overlay', !(await page.locator('#panelOverlay').isVisible()));
  }
  await page.locator('#iconBoardButton').click();
  await page.waitForTimeout(350);
  check('five plugin icon family', await page.locator('.family-item').count() === 5);
  await page.screenshot({ path: path.join(ROOT, '08-icon-family.png') });
  await page.locator('#closeIcons').click(); await page.waitForTimeout(200);
  await page.setViewportSize({ width: 390, height: 844 });
  check('no horizontal overflow at 390px', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(ROOT, '09-mobile.png'), fullPage: true });
  await page.evaluate(() => window.preview.openPanel('radialdots')); await page.waitForTimeout(320);
  check('mobile panel fits', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.keyboard.press('Escape'); await page.waitForTimeout(200);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.evaluate(() => window.preview.openPanel('stripe')); await page.waitForTimeout(10);
  check('reduced motion transition', await page.locator('.preview-shell').evaluate(e => parseFloat(getComputedStyle(e).transitionDuration) < .01));
  await page.keyboard.press('Escape'); await page.waitForTimeout(200);
  check('zero browser runtime errors', errors.length === 0, errors.join(' | '));
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'original-source-manifest.json'), 'utf8').replace(/^\uFEFF/, ''));
  const changed = manifest.filter(f => !fs.existsSync(f.path) || hash(f.path) !== f.sha256);
  check('original installer UI and shared theme unchanged', !changed.some(f => /CenterForm\.cs$|shared[\\/]PanelTheme\.cs$/.test(f.path)), manifest.length + ' files compared; concurrent differences=' + changed.length);
  await browser.close();
  const report = { timestamp: new Date().toISOString(), previewOnly: true, backendConnected: false, checks, errors, originalSourceFiles: manifest.length, changedOriginalFiles: changed.map(f => f.path), originalSnapshotNote: 'Eight original project files changed concurrently after the initial snapshot. This UI-preview task and its workers wrote only E:/IVAN-LiquidGlass-preview. Concurrent source changes were not reverted. No all-original-files-unchanged claim is made.', screenshots: fs.readdirSync(ROOT).filter(x => x.endsWith('.png')) };
  fs.writeFileSync(path.join(ROOT, 'browser-verification.json'), JSON.stringify(report, null, 2));
  fs.writeFileSync(path.join(ROOT, 'VERIFICATION.txt'), 'IVAN CENTER UI PREVIEW\nNo installer/Rhino operations executed.\nCommand: node E:\\IVAN-LiquidGlass-preview\\verify-preview.cjs\nInput: file:///E:/IVAN-LiquidGlass-preview/index.html\n' + checks.map(c => (c.ok ? 'PASS ' : 'FAIL ') + c.name + ' | ' + c.detail).join('\n') + '\nLiteral browser stderr/page errors: ' + JSON.stringify(errors) + '\n');
  process.exitCode = checks.some(c => !c.ok) ? 1 : 0;
})().catch(e => { console.error(e.stack); process.exitCode = 1; });
