<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>iconmake</AssemblyName>
    <RootNamespace>IconMake</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <DebugType>none</DebugType>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <NoWarn>CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Drawing" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
